name: slack

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple command
        run: echo "Hello from GitHub Actions!"
